# Generated by Django 4.2.6 on 2023-10-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': 'Article-4', 'verbose_name_plural': 'Article-4'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Category-1', 'verbose_name_plural': 'Category-1'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created'], 'verbose_name': 'Module-3', 'verbose_name_plural': 'Module-3'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created'], 'verbose_name': 'Topic-2', 'verbose_name_plural': 'Topic-2'},
        ),
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(blank=True, choices=[('dark', 'dark'), ('light', 'light'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], max_length=10, null=True),
        ),
    ]
